---
# tasks file for postgresql

- name: install postgresql
  yum:
    name: "{{ postgresql_packages }}"
    state: latest

- name: open the firewall port
  firewalld:
    state: enabled
    port: "{{ postgresql_port }}/tcp"
    permanent: true
    immediate: true
  when: not ansible_check_mode

- name: check if postgresql is installed
  stat:
    path: "{{ postgresql_data_dir }}"
  register: check_postgrsql_data_dir
  ignore_errors: true

- name: initialize database
  shell: postgresql-setup initdb
  when: check_postgrsql_data_dir is not defined
