---
# tasks file for postgresql

- name: install postgresql
  yum:
    name: "{{ postgresql_packages }}"
    state: latest

- name: open the firewall port
  firewalld:
    state: enabled
    port: "{{ postgresql_port }}/tcp"
    permanent: true
    immediate: true
  when: not ansible_check_mode
