---
# tasks file for postgresql

- import_tasks: install.yml
  tags: install_postgresql
  when: postgresql_installed == true

- import_tasks: remove.yml
  tags: remove_postgresql
  when: postgresql_installed == false
