---
# tasks file for postgresql

- import_tasks: installation.yml
  tags: install_postgresql
  when: postgresql_installed == true

- import_tasks: removal.yml
  tags: remove_postgresql
  when: postgresql_installed == false
