---
# tasks file for haproxy

- include_vars: "{{ item }}"
  with_items:
  - "../../tomcat/defaults/main.yml"

- name: install HAProxy
  yum:
    name: "{{ haproxy_packages }}"
    state: latest

- name: open the firewall port
  firewalld:
    state: enabled
    port: "{{ haproxy_port }}/tcp"
    permanent: true
    immediate: true
  when: not ansible_check_mode

- name: generate haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_conf_dir }}/haproxy.cfg"

- name: restart haproxy service
  systemd:
    name: haproxy
    state: restarted
    enabled: true

- name: check http response
  uri:
    url: http://{{ ansible_host }}:{{ haproxy_port }}
    return_content: true
  register: haproxy_result
  until: haproxy_expected_response in haproxy_result.content
  retries: 3
  delay: 3
  when: not ansible_check_mode
