---

- hosts: tag_AnsibleGroup_frontends
  gather_facts: false
  vars_files:
    - roles/osp-setup/defaults/main.yml
    - roles/haproxy/defaults/main.yml
  tasks:
    - name: check http response
      uri:
        url: "http://frontend1.{{ ANSIBLE_ADVANCE_GUID }}.example.opentlc.com"
        return_content: true
      register: webpage
      until: haproxy_expected_response in webpage.content
      retries: 3
      delay: 3

    - name: fail if expected result is not in the page content
      fail:
      when: "haproxy_expected_response not in webpage.results[0].content"
