---

- hosts: frontends
  gather_facts: false
  vars_files:
    - roles/osp-setup/defaults/main.yml
    - roles/haproxy/defaults/main.yml
  post_tasks:
    - name: check http response
      uri:
        url: "http://{{ item.public_v4 }}/"
        return_content: true
      register: webpage
      until: haproxy_expected_response in webpage.content
      retries: 3
      delay: 3
      with_items: "{{ frontend_instance.ansible_facts.openstack_servers }}"

    - name: fail if expected result is not in the page content
      fail:
      when: "haproxy_expected_response not in webpage.results[0].content"
