---

- hosts: tag_AnsibleGroup_frontends
  connection: local
  gather_facts: false
  vars_files:
    - roles/haproxy/defaults/main.yml
  tasks:
    - name: check http response
      uri:
        url: "http://{{ inventory_hostname }}"
        return_content: true
      register: webpage
      until: haproxy_expected_response in webpage.content
      retries: 3
      delay: 3

    - name: fail if expected result is not in the page content
      fail:
      when: "haproxy_expected_response not in webpage.content"
