---

- name: get instance facts and add hosts to group
  hosts: workstation
  gather_facts: true
  roles:
    - { role: osp-facts }

- name: setup database server
  hosts: appdbs
  gather_facts: false
  become: true
  roles:
    - { role: postgresql }

- name: setup applicaton server
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - { role: tomcat }

- name: setup load-balancer
  hosts: frontends
  gather_facts: true
  become: true
  roles:
    - { role: haproxy }
