= Ansible Tower Homework Lab Instruction

== Prerequisites

First deploy the following environments through the OpenTLC lab.

* _Ansible Advanced - Homework_
* _Ansible Advanced - OpenStack_

NOTE: The OpenTLC lab has limits that only 3 labs can be deployed.
This homework deploys 3 labs finally, so remove all the labs in advance if you've already had any.

* Connect to the workstation host for _Ansible Advanced - Homework_.

[source,text]
----
HOMEWORK_GUID=<Ansible Tower Homework GUID from mail>
OPENTLC_USERNAME=<Your OpenTLC user name>
ssh ${OPENTLC_USERNAME}@bastion.${HOMEWORK_GUID}.example.opentlc.com
scp ~/.ssh/<OPENTLC_KEY> ${OPENTLC_USERNAME}@bastion.${HOMEWORK_GUID}.example.opentlc.com:/tmp/mykey.pem
----

NOTE: Specify `~/.ssh/<OPENTLC_KEY>` with your OpenTLC ssh key file.

* Set up credentials and variables for the playbook.

[source,text]
----
sudo -i
mv /tmp/mykey.pem ~/.ssh/
echo "OSP_GUID=<OpenStack GUID from mail>" >> ~/.bashrc
source ~/.bashrc
OPENTLC_USERNAME=<Your OpenTLC user name>
----

* Set up the workstation host for _Ansible Advanced - OpenStack_.

[source,text]
----
git clone https://github.com/hashnao/ansible_advance_homework.git
cd ansible_advance_homework/
sed -i "s/OSP_GUID/${OSP_GUID}/" ssh.cfg
ansible-playbook qa-setup-workstation.yml \
-e OSP_GUID=${OSP_GUID} \
--ask-vault-pass \
--private-key=/root/.ssh/mykey.pem \
-u ${OPENTLC_USERNAME}
----

NOTE: Enter the vault password that encrypts `keystone_password`.

[source,text]
----
Vault password:
----


== Configuring Ansible Tower

* Create a credential file for OpenTLC.

[source,text]
----
ansible-vault create /tmp/opentlc.yml
----

NOTE: Enter your OpenTLC ID and password as the prompt appears.

----
opentlc_username: <OpenTLC user name>
opentlc_password: <OpenTLC password>
----


* Remove unnecessary line in the key file.

[source,text]
----
vi /root/.ssh/openstack.pem
----

* Create Ansible Tower job templates.

[source,text]
----
cat >> ~/.bashrc << EOF
export GITHUB_REPO=https://github.com/hashnao/ansible_advance_homework.git
export REGION=us-east-1
export RH_MAIL_ID=<your mail id for dynamic inventory tag>
export TOWER_GUID=<Ansible Tower Homework GUID from mail>"
EOF
source ~/.bashrc
ansible-playbook setup-tower.yml \
-e TOWER_GUID=${TOWER_GUID} \
-e OSP_GUID=${OSP_GUID} \
-e REGION_NAME=${REGION} \
-e EMAIL=${RH_MAIL_ID} \
-e github_repo=${GITHUB_REPO} \
-e @/tmp/opentlc.yml \
--ask-vault-pass
----


== Running a workflow template on Ansible Tower


== Manual deployment

This section describes about manually running the playbooks for debugging, verifying, or other purposes.

=== Provisioning QA Environment

* Connect to the workstation host for _Ansible Advanced - Homework_.

[source,text]
----
HOMEWORK_GUID=<Ansible Tower Homework GUID from mail>
OPENTLC_USERNAME=<Your OpenTLC user name>
ssh ${OPENTLC_USERNAME}@bastion.${HOMEWORK_GUID}.example.opentlc.com
scp ~/.ssh/<OPENTLC_KEY> ${OPENTLC_USERNAME}@bastion.${HOMEWORK_GUID}.example.opentlc.com:/tmp/mykey.pem
----

NOTE: Specify `~/.ssh/<OPENTLC_KEY>` with your OpenTLC ssh key file.

* Set up the workstation host for _Ansible Advanced - OpenStack_.

[source,text]
----
sudo -i
mv /tmp/mykey.pem ~/.ssh/
echo "OSP_GUID=<OpenStack GUID from mail>" >> ~/.bashrc
. ~/.bashrc
OPENTLC_USERNAME=<Your OpenTLC user name>
git clone https://github.com/hashnao/ansible_advance_homework.git
cd ansible_advance_homework/
sed -i "s/OSP_GUID/${OSP_GUID}/" ssh.cfg
ansible-playbook qa-setup-workstation.yml \
-e OSP_GUID=${OSP_GUID} \
--ask-vault-pass \
--private-key=/root/.ssh/mykey.pem \
-u ${OPENTLC_USERNAME}
----

NOTE: Enter the vault password that encrypts `keystone_password`.

[source,text]
----
Vault password:
----

* Provision instances for QA Environment on _Ansible Advanced - OpenStack_.

[source,text]
----
ansible-playbook qa-setup-instances.yml -e OSP_GUID=${OSP_GUID}
----

* Install the 3-tier applications.

[source,text]
----
ansible-playbook qa-3tier-setup.yml
----

* run a smoke test on the QA environment for the three-tier application

[source,text]
----
ansible-playbook qa-smoke-test.yml
----

NOTE: If the smoke test fails and you need to re-create the QA Environment,
you can delete the instances by running the folloing playbook.

[source,text]
----
ansible-playbook qa-clean-instances.yml -e OSP_GUID=${OSP_GUID}
----


=== Provisioning Production Environment

* Create a credential file for OpenTLC.

[source,text]
----
ansible-vault create /tmp/opentlc.yml
----

NOTE: Enter your OpenTLC ID and password as the prompt appears.

----
opentlc_username: <OpenTLC user name>
opentlc_password: <OpenTLC password>
----

[source,text]
----
ansible-playbook prod-setup-instances.yml \
-e @/tmp/opentlc.yml \
--ask-vault-pass
----


== Description of Ansible Playbooks

.Playbooks
[%header,cols=2*]
|===
| Files | Description
| `qa-setup-workstation.yml` | configures workstation for OpenStack, creates prerequisite resources, and installs isolated node for Ansible Tower.
| `qa-setup-instances.yml` | creates instances for QA Environment.
| `qa-clean-instances.yml` | removes instances for QA Environment.
| `qa-smoke-test.yml` | runs smoke test for QA Environment.
| `qa-3tier-setup.yml` | installs the 3-tier application for QA environment.
| `clean-3tier-app.yml` | removes the 3-tier application for QA environment.
| `prod-setup-instances.yml` | creates instances for production environment.
| `prod-3tier-setup.yml` | installs the 3-tier application for production environment.
| `prod-smoke-test.yml` | runs smoke test for production environment.
| `setup-tower.yml` | creates Ansible Tower job templates and workflows.
| `prod-setup-credentials.yml` | fetches key.pem from bastion and creates machine credential to connect to instances.
| `prod-check-ssh.yml` | checks ssh connection with instances.
|===

.Roles
[%header,cols=2*]
|===
| File or directory | Description
| `roles/base` | configures yum repository and installs base packages.
| `roles/tomcat` | installs Tomcat.
| `roles/postgresql` | installs PostgreSQL.
| `roles/haproxy` | installs HAProxy.
| `roles/setup-workstation` | sets up workstation for OpenStack, creates prerequisite objects including network, ssh keypair, security groups.
| `roles/osp-servers` | provisions instances on OpenStack for 3-tier applications.
| `roles/osp-instance-delete` | removes instances on OpenStack.
| `roles/osp-facts` | generates in-memory inventory for instances on OpenStack.
| `roles/config-tower` | creates Ansible Tower job templates and workflows.
| `roles/config-tower/vars/main.yml` | contains the variables for Ansible Tower. DO NOT make any changes in the file.
| `roles/config-tower/tasks/ec2_dynamic.yml | creates Dynamic inventory in Ansible tower. Use `AWS Access Key` for credential.
| `roles/config-tower/tasks/job_template.yml | creates job templates.
| `roles/config-tower/tasks/workflow_template.yml | creates workflow based on `templates/workflow.yml.j2`.
| `roles/config-tower/tasks/post-config-tower.yml | sets up project, inventories, or credentials.
|===
