- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts

- name: setup load-balancer
  hosts: frontends
  gather_facts: false
  become: true
  roles:
  - { role: haproxy }

- name: setup applicaton server
  hosts: apps
  gather_facts: false
  become: true
  roles:
  - { role: tomcat }

- name: setup database server
  hosts: appdbs
  gather_facts: false
  become: true
  roles:
  - { role: postgresql }
