---
# vars file for roles/config-tower

tower_static_inventory_name: scm_inventory
tower_static_inventory_variable: static_inventory_variable.yml
tower_ec2_dynamic_inventory: "AWS inventory source"
tower_ec2_inventory_source: "Three tier inventory source"
tower_ec2_dynamic_inventory_variable: ec2_dynamic_inventory_variable.yml
tower_ec2_dynamic_inventory_variable_group: ec2_dynamic_inventory_variable_group.yml
scm_inventory_source: "SCM three tier inventory source"
tower_tmp_dir: /tmp

tower_job_template_provision_qa: "QA environment - provisioning"
tower_playbook_provision_qa: qa-setup-instances.yml
tower_job_template_delete_qa: "QA environment - nuke"
tower_playbook_delete_qa: qa-clean-instances.yml
tower_job_template_smoke_qa: "QA environment - smoke test"
tower_playbook_smoke_qa: qa-smoke-test.yml
tower_job_template_provision_prod: "Production environment - provisioning"
tower_playbook_provision_prod: prod-setup-instances.yml
tower_job_template_ssh_prod: "Production environment - configuring ssh keys, provisioning 3-tier application, running smoke test"
tower_playbook_ssh_prod: prod-setup-credentials.yml
tower_job_template_3tier_app: "QA environment - 3-tier application deployment"
tower_playbook_3tier_app: qa-3tier-setup.yml
tower_job_template_smoke_prod: "Production environment - smoke test"
tower_playbook_smoke_prod: prod-smoke-test.yml
tower_job_template_status_prod: "Production environment - ec2 instances status check"
tower_playbook_status_prod: prod-check-ssh.yml
tower_job_template_3tier_app_prod: "Production environment - 3-tier application deployment"
tower_playbook_3tier_app_prod: prod-3tier-setup.yml

tower_project_name: "Homework Assignment"
tower_organization: Default
tower_username: admin
tower_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38373133633866623065616536393430353832653162653731663462303863623634333564373033
          6232643962336163346536306630346232313165303738380a393735633433613738386631306638
          30303262623562656230303865393464346161376235643739386635326464346365313166313936
          6332303661396539640a303564323238323465306436316361613831346233626162343165636236
          3965
tower_ssh_cred_name: "Connect_to_workstation"
tower_ssh_username: cloud-user
tower_ssh_ec2_username: ec2-user
tower_ssh_secretkey_path: /root/.ssh/openstack.pem
tower_opentlc_secretkey_path: /root/.ssh/mykey.pem
tower_aws_read_keys: "AWS Access Key"
tower_aws_cred_name: "Credentials of ec2 instances"
tower_aws_region_name: "{{ REGION_NAME }}"
tower_tag_filters: "tag:instance_filter=three-tier-app-{{ EMAIL }}"
tower_opentlc_cred_name: "Opentlc key"
tower_vault_credential: yum-repo-cred
vault_name: yum_repo_vault
tower_playbook_vault_name: playbook-vault
tower_group_name: workstation
tower_host_name: workstation-{{ OSP_GUID }}.rhpds.opentlc.com
tower_ec2_dynamic_inventory_group:
  - apps
  - appdbs
  - frontends
  - bastions
tower_ec2_dynamic_tag: tag_AnsibleGroup
tower_instance_group_name: osp
tower_workflow_template: cicd
# TBC: Check if it's used.
tower_scm_type: git
tower_scm_branch: master
tower_scm_url: "{{ github_repo }}"
path_to_scm_inventory: scm_inventory
opentlc_repo_url: http://www.opentlc.com/download/ansible_bootcamp
