---

- name: create Dynamic Inventory
  tower_inventory:
    name: "{{ tower_ec2_dynamic_inventory }}"
    organization: "{{ tower_organization }}"
    tower_verify_ssl: false

- name: create groups to deploy applications
  tower_group:
    name: "{{ item }}"
    inventory: "{{ tower_ec2_dynamic_inventory }}"
    tower_verify_ssl: false
  with_items: "{{ tower_ec2_dynamic_inventory_group }}"

- name: create groups with AWS tag to deploy applications
  tower_group:
    name: "{{ tower_ec2_dynamic_tag }}-{{ item }}"
    inventory: "{{ tower_ec2_dynamic_inventory }}"
    tower_verify_ssl: false
  with_items: "{{ tower_ec2_dynamic_inventory_group }}"

- name: associate AWS tags as children to {{ item }} group
  command: |
    tower-cli group associate --group "{{ tower_ec2_dynamic_tag }}-{{ item }}" \
    --parent "{{ item }}" --inventory "{{ tower_ec2_dynamic_inventory }}"
  with_items: "{{ tower_ec2_dynamic_inventory_group }}"

- name: create dynamic inventory variables file
  template:
    src: "{{ tower_ec2_dynamic_inventory_variable }}.j2"
    dest: "@{{ tower_tmp_dir }}/{{ tower_ec2_dynamic_inventory_variable }}"

- name: add localhost as host
  tower_host:
    name: localhost
    inventory: "{{ tower_ec2_dynamic_inventory }}"
    variables: "@{{ tower_tmp_dir }}/{{ tower_ec2_dynamic_inventory_variable }}"
    tower_verify_ssl: false

- name: create inventory source with ec2 script
  tower_inventory_source:
    name: "{{ tower_ec2_inventory_source }}"
    inventory: "{{ tower_ec2_dynamic_inventory }}"
    source: ec2
    credential: "{{ tower_aws_read_keys }}"
    source_regions: "{{ tower_aws_region_name }}"
    instance_filters: "{{ tower_tag_filters }}"
    overwrite: true
    update_on_launch: true
    tower_verify_ssl: false
