---

- name: create Dynamic Inventory
  tower_inventory:
    name: "{{ tower_ec2_dynamic_inventory }}"
    organization: "{{ tower_organization }}"

- name: create groups to deploy applications
  tower_group:
    name: "{{ item }}"
    inventory: "{{ tower_ec2_dynamic_inventory }}"
  loop:
    - "{{ tower_ec2_dynamic_inventory_group_first }}"
    - "{{ tower_ec2_dynamic_inventory_group_second }}"

- name: associate AWS tags as children to {{ item }} group
  command: |
    tower-cli group associate --group {{ item }} --parent bastions \
    --inventory "{{ tower_ec2_dynamic_inventory }}"
  loop: "{{ tower_ec2_dynamic_inventory_group_second }}"

- name: copy inventory vars
  copy:
    src: inventory_vars.json
    dest: "{{ tower_tmp_dir }}/inventory_vars.json"

- name: add localhost as host
  tower_host:
    name: localhost
    inventory: "{{ tower_ec2_dynamic_inventory }}"
    variables: "@{{ tower_tmp_dir }}/inventory_vars.json"

- name: create inventory source with ec2 script
  tower_inventory_source:
    name: "{{ tower_ec2_inventory_source }}"
    inventory: "{{ tower_ec2_dynamic_inventory }}"
    source: ec2
    credential: "{{ tower_aws_read_keys }}"
    source_regions: "{{ tower_aws_region_name }}"
    instance_filters: "{{ tower_tag_filters }}"
    overwrite: true
    update_on_launch: true
