---

- name: create create job template for OpenStack instances
  tower_job_template:
    name: "{{ tower_job_template_osp_instances }}"
    job_type: run
    inventory: "{{ tower_static_inventory_name }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_osp_instances }}"
    credential: "{{ tower_ssh_cred_name }}"

# TBC: check if it can be replaced with related module.
- name: associate IG to OSP instances job template
  shell: |
    tower-cli job_template associate_ig \
    --job_template "{{ tower_job_template_osp_instances }}"
    --instance_group "{{ tower_instance_group_name }}"

- name: create vault credential
  tower_credential_type:
    name: yum-repo-cred
    organization: "{{ tower_organization }}"
    inputs: "{'vault_password': 'ansible'}"
    type: vault

- name: create job template for 3tier app deploy on QA Env
  tower_job_template:
    name: "{{ tower_job_template_3tier_app }}"
    job_type: run
    inventory: "{{ tower_static_inventory_name }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_app_deploy }}"
    credential: "{{ tower_ssh_cred_name }}"
    vault_credential: yum-repo-cred

# TBC: check if it can be replaced with related module.
- name: associate IG to 3tier job template
  shell: |
    tower-cli job_template associate_ig \
    --job_template "{{ tower_job_template_3tier_app }}" \
    --instance_group "{{ tower_instance_group_name }}"

- name: Job template to delete OSP Instances
  tower_job_template:
    name: "{{ tower_job_template_osp_instances_delete }}"
    job_type: run
    inventory: "{{ tower_static_inventory_name }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_osp_instances_delete }}"
    credential: "{{ tower_ssh_cred_name }}"

# TBC: check if it can be replaced with related module.
- name: associate IG to OSP Delete instances job template
  shell: |
    tower-cli job_template associate_ig \
    --job_template "{{ tower_job_template_osp_instances_delete }}" \
    --instance_group "{{ tower_instance_group_name }}"

- name: create job template for smoke test osp instances
  tower_job_template:
    name: "{{ tower_job_template_smoke_osp }}"
    job_type: run
    inventory: "{{ tower_static_inventory_name }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_smoke_osp }}"
    credential: "{{ tower_ssh_cred_name }}"

# TBC: check if it can be replaced with related module.
- name: associate IG to Smoke test job template
  shell: |
    tower-cli job_template associate_ig \
    --job_template "{{ tower_job_template_smoke_osp }}" \
    --instance_group "{{ tower_instance_group_name }}"

- name: generate var file for order_svc.sh script
  template:
    src: aws_jq_vars.yml.j2
    dest: "{{ tower_tmp_dir }}/aws_jq_vars.yml"

- name: create job template for provisioning AWS environment
  tower_job_template:
    name: "{{ tower_job_template_aws_provision }}"
    job_type: run
    inventory: "{{ tower_static_inventory_name }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_aws_provision }}"
    credential: "{{ tower_ssh_cred_name }}"
    extra_vars_path: "{{ tower_tmp_dir }}/aws_jq_vars.yml"

- name: generate var file for tower module
  template:
    src: tower_info.yml.j2
    dest: "{{ tower_tmp_dir }}/tower_info.yml"

- name: create job template for injecting AWS SSH keys
  tower_job_template:
    name: "{{ tower_job_template_aws_ssh_keys }}"
    job_type: run
    inventory: "{{ tower_ec2_dynamic_inventory}}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_aws_ssh }}"
    credential: "{{ tower_opentlc_cred_name }}"
    extra_vars_path: /tmp/tower_info.yml

- name: create job template for checking AWS instances status
  tower_job_template:
    name: "{{ job_template_aws_status_check }}"
    job_type: run
    inventory: "{{ tower_ec2_dynamic_inventory }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_aws_status }}"
    credential: "{{ tower_opentlc_cred_name }}"

- name: create job template for 3tier AWS deploy
  tower_job_template:
    name: "{{ tower_job_template_3tier_app_aws }}"
    job_type: run
    inventory: "{{ tower_ec2_dynamic_inventory }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_app_deploy }}"
    credential: "{{ tower_ssh_cred_name }}"
    vault_credential: yum-repo-cred

- name: create job template for smoke test aws instances
  tower_job_template:
    name: "{{ tower_job_template_smoke_aws }}"
    job_type: run
    inventory: "{{ tower_ec2_dynamic_inventory }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_aws_smoke_app }}"
    credential: "{{ tower_ssh_cred_name }}"
    vault_credential: yum-repo-cred
