---

- name: create job template for provisioning QA environment
  tower_job_template:
    name: "{{ tower_job_template_provision_qa }}"
    job_type: run
    inventory: "{{ tower_static_inventory_name }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_provision_qa }}"
    credential: "{{ tower_ssh_cred_name }}"
    tower_verify_ssl: false

# TBC: check if it can be replaced with related module.
- name: associate instance group to job template for provisioning QA environment
  shell: |
    tower-cli job_template associate_ig \
    --job-template "{{ tower_job_template_provision_qa }}" \
    --instance-group "{{ tower_instance_group_name }}"

- name: create vault credential
  command: |
    tower-cli credential create --organization "{{ tower_organization }}" \
    --name "{{ tower_vault_credential }}" \
    --inputs='{"vault_password":"ansible"}' \
    --credential-type="Vault"

- name: create job template for 3-tier application on QA environment
  tower_job_template:
    name: "{{ tower_job_template_3tier_app }}"
    job_type: run
    inventory: "{{ tower_static_inventory_name }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_3tier_app }}"
    credential: "{{ tower_ssh_cred_name }}"
    vault_credential: "{{ tower_vault_credential }}"
    tower_verify_ssl: false

# TBC: check if it can be replaced with related module.
- name: associate instance group to job template for 3 tier application on QA environment
  shell: |
    tower-cli job_template associate_ig \
    --job-template "{{ tower_job_template_3tier_app }}" \
    --instance-group "{{ tower_instance_group_name }}"

- name: create job template for deleting QA environment
  tower_job_template:
    name: "{{ tower_job_template_delete_qa }}"
    job_type: run
    inventory: "{{ tower_static_inventory_name }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_delete_qa }}"
    credential: "{{ tower_ssh_cred_name }}"
    tower_verify_ssl: false

# TBC: check if it can be replaced with related module.
- name: associate instance group to job template for deleting QA environment
  shell: |
    tower-cli job_template associate_ig \
    --job-template "{{ tower_job_template_delete_qa }}" \
    --instance-group "{{ tower_instance_group_name }}"

- name: create job template for smoke test on QA environment
  tower_job_template:
    name: "{{ tower_job_template_smoke_qa }}"
    job_type: run
    inventory: "{{ tower_static_inventory_name }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_smoke_qa }}"
    credential: "{{ tower_ssh_cred_name }}"
    tower_verify_ssl: false

# TBC: check if it can be replaced with related module.
- name: associate instance group to job template for smoke test on QA environment
  shell: |
    tower-cli job_template associate_ig \
    --job-template "{{ tower_job_template_smoke_qa }}" \
    --instance-group "{{ tower_instance_group_name }}"

- name: generate var file for order_svc.sh script
  template:
    src: aws_jq_vars.yml.j2
    dest: "{{ tower_tmp_dir }}/aws_jq_vars.yml"

- name: create job template for provisioning production environment
  tower_job_template:
    name: "{{ tower_job_template_provision_prod }}"
    job_type: run
    inventory: "{{ tower_static_inventory_name }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_provision_prod }}"
    credential: "{{ tower_ssh_cred_name }}"
    extra_vars_path: "{{ tower_tmp_dir }}/aws_jq_vars.yml"
    tower_verify_ssl: false

- name: generate var file for tower module
  template:
    src: tower_info.yml.j2
    dest: "{{ tower_tmp_dir }}/tower_info.yml"

- name: create job template for configuring ssh keys for production environment
  tower_job_template:
    name: "{{ tower_job_template_ssh_prod }}"
    job_type: run
    inventory: "{{ tower_ec2_dynamic_inventory }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_ssh_prod }}"
    credential: "{{ tower_opentlc_cred_name }}"
    vault_credential: "{{ tower_playbook_vault_name }}"
    extra_vars_path: /tmp/tower_info.yml
    tower_verify_ssl: false

- name: create job template for checking instances status for production environment
  tower_job_template:
    name: "{{ tower_job_template_status_prod }}"
    job_type: run
    inventory: "{{ tower_ec2_dynamic_inventory }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_status_prod }}"
    credential: "{{ tower_opentlc_cred_name }}"
    tower_verify_ssl: false

- name: create job template for 3tier application for production environment
  tower_job_template:
    name: "{{ tower_job_template_3tier_app_prod }}"
    job_type: run
    inventory: "{{ tower_ec2_dynamic_inventory }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_3tier_app_prod }}"
    credential: "{{ tower_ssh_cred_name }}"
    vault_credential: "{{ tower_vault_credential }}"
    tower_verify_ssl: false

- name: create job template for smoke test on production environment
  tower_job_template:
    name: "{{ tower_job_template_smoke_prod }}"
    job_type: run
    inventory: "{{ tower_ec2_dynamic_inventory }}"
    project: "{{ tower_project_name }}"
    playbook: "{{ tower_playbook_smoke_prod }}"
    credential: "{{ tower_ssh_cred_name }}"
    vault_credential: "{{ tower_vault_credential }}"
    tower_verify_ssl: false
