---

- name: create CICD workflow
  tower_workflow_template:
    name: "{{ tower_workflow_template }}"
    organization: "{{ tower_organization }}"
    tower_verify_ssl: false

- name: create workflow schema
  template:
    src: workflow.yml.j2
    dest: "{{ tower_tmp_dir }}/workflow.yml"

- name: create workflow using schema
  tower_workflow_template:
    name: "{{ tower_workflow_template }}"
    schema: "{{ lookup('file', '{{ tower_tmp_dir }}/workflow.yml') }}"
    tower_verify_ssl: false
