---
# tasks file for tomcat

- import_tasks: installation.yml
  tags: install_tomcat
  when: tomcat_installed == true

- import_tasks: removal.yml
  tags: remove_tomcat
  when: tomcat_installed == false
